# Docker composer file for Linux Rust (Alpine Based)
version: '3.8'
services:
  linux-rust:
    image: "ghcr.io/fvincenzo/linux-rust-alpine:latest"
    container_name: "linux-rust-alpine"
    volumes:
      - ./workspace:/workspace
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.gitconfig:/root/.gitconfig
    tty: true
    restart: unless-stopped